// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package dependency_injection

import (
	"stock-challenge-go/pkg/api"
	"stock-challenge-go/pkg/config"
)

// Injectors from wire.go:

func InitializeAPI(cfg config.Config) (*http.ServerHTTP, error) {
	serverHTTP := http.NewServerHTTP()
	return serverHTTP, nil
}
